### PR TITLE
SDL integration

### PR DESCRIPTION
**Pull request by daigennki**
With these changes, GLFW code is replaced with the SDL equivalent when the VPR_USE_SDL macro is defined by enabling the VPR_USE_SDL CMake option. I figured other people might want to use this with SDL as well, hence why I am making this pull request.

### CODE REVIEW

**Comment by fuchstraumer** [comment]
Oh wow, I missed this entirely! Sorry for missing this for THREE weeks. Let me examine this after work today, and I'll try to pull it in. I was going to make some changes to anonymize GLFW away a bit anyways, since as convenient as it is I was worried about making this exact scenario more difficult.

**Comment by daigennki** [comment]
No worries, I understand you're pretty busy!

**Comment by fuchstraumer** [comment]
I'm merging it for now, and will probably make a few changes off of this. I'll notify you when those are done.

**Comment by fuchstraumer** [comment]
@daigennki I didn't end up feeling the need for any changes, though I might look into how you could make things more robust than just trusting SDL to be an include directory. That might apply to higher levels of your work though. 

I'm curious, how have you found using this library? I'd always like to hear ideas for improvements people would like to see. Recent commits stripped out the unused alloc library stuff (if you need similar things, use VMA. I can help with that if need be), and cleaned up the formatting to match the style I prefer nowadays (closer to work style, so I don't confuse my brain lol)

**Comment by daigennki** [comment]
I made SDL included that way because it isn't (officially) hosted through git, but yeah, I myself feel like there might be a better way to go about that.
And sorry, although I do like this library, I ended up not using this library since I wanted to learn more about how Vulkan works, and there's the whole deal with the allocation stuff. I do think it is nicely made though, nicely formatted and easy to understand. 
As for suggestions, I noticed pointers to required parameters (such as the parent `Device`) being used despite this being C++ only. I personally would rather use a reference then get the address to that (`&_device`), but if that's not your style, that's fine. Maybe also try not to expose internal handles as much as possible by using stuff like `friend` or nested classes? That might be a bit far-fetched though.

**Pull request merged**
